// Todos los textos de UI en español (es-AR).
// Ningún componente debe tener strings hardcodeados; siempre importar desde acá.

export const copy = {
  general: {
    loading:   'Cargando...',
    error:     'Ocurrió un error',
    noData:    'Sin datos',
    save:      'Guardar',
    cancel:    'Cancelar',
    edit:      'Editar',
    delete:    'Eliminar',
    confirm:   'Confirmar',
    back:      'Volver',
    search:    'Buscar',
    filter:    'Filtrar',
    create:    'Crear',
    update:    'Actualizar',
    close:     'Cerrar',
    actions:   'Acciones',
    optional:  '(opcional)',
    required:  'Campo requerido',
    yes:       'Sí',
    no:        'No',
    logoAlt:   'Logo First Blades',
  },

  auth: {
    login: {
      welcome:             'Bienvenido',
      subtitle:            'Portal First Blades',
      brandTagline:        'Portal de operaciones de campo',
      email:               'Correo electrónico',
      emailPlaceholder:    'nombre@empresa.com',
      password:            'Contraseña',
      showPassword:        'Mostrar contraseña',
      hidePassword:        'Ocultar contraseña',
      submit:              'Ingresar',
      forgotPassword:      '¿Olvidaste tu contraseña?',
      secureAccess:        'Acceso seguro · First Blades',
      invalidCredentials:  'Correo o contraseña incorrectos.',
      genericError:        'Error al iniciar sesión. Intentá de nuevo.',
    },
    logout: 'Cerrar sesión',
  },

  nav: {
    miPerfil:         'Mi Perfil',
    equipo:           'Equipo',
    miEquipo:         'Mi Equipo',
    calendario:       'Calendario',
    solicitudPasaje:  'Solicitud de Pasaje',
    solicitudAusencia:'Solicitud de Ausencia',
    aprobaciones:     'Aprobaciones',
    procedimientos:   'Procedimientos / Políticas',
    rendicionGastos:  'Rendición de Gastos',
    gestionUsuarios:  'Gestión de Usuarios',
  },

  placeholder: {
    externalLink:      'Accedé a tu Rendición de Gastos en Google Workspace.',
    externalBtn:       'Abrir en Google Workspace',
    externalPending:   'Enlace pendiente de configuración.',
  },

  status: {
    pendiente:             'Pendiente',
    aprobado:              'Aprobado',
    rechazado:             'Rechazado',
    activo:                'Activo',
    inactivo:              'Inactivo',
    trabajando:            'Trabajando',
    en_viaje:              'En viaje',
    en_franco:             'En franco',
    periodo_fuera_trabajo: 'Fuera del trabajo',
    editada:               'Editada',
    cancelada:             'Cancelada',
    vigente:               'Vigente',
    archivado:             'Archivado',
  },

  roles: {
    admin:      'Administrador',
    supervisor: 'Supervisor',
    empleado:   'Empleado',
  },

  purgatorio: {
    infoMessage:      'Tu solicitud será revisada por Administración.',
    pendingMessage:   'Tu solicitud está siendo revisada.',
    approvedMessage:  'Tu solicitud fue aprobada.',
    rejectedMessage:  'Tu solicitud fue rechazada.',
    motivo:           'Motivo del rechazo',
  },

  gestionUsuarios: {
    title:    'Gestión de Usuarios',
    subtitle: 'Administrá los usuarios del portal',
    createUser: 'Crear usuario',
    editUser:   'Editar usuario',
    passwordRequired: 'La contraseña inicial es requerida.',
    table: {
      nombre:      'Nombre',
      email:       'Correo electrónico',
      rol:         'Rol',
      supervisor:  'Supervisor',
      estado:      'Estado',
      ingreso:     'Ingreso',
      acciones:    'Acciones',
    },
    form: {
      nombre:              'Nombre completo',
      nombrePlaceholder:   'Nombre completo',
      email:               'Correo electrónico',
      rol:                 'Rol',
      supervisor:          'Supervisor',
      supervisorPlaceholder: 'Seleccioná un supervisor',
      supervisorHint:      'Solo visible si el rol es Empleado',
      password:            'Contraseña inicial',
      passwordHint:        'El usuario podrá cambiarla después del primer ingreso',
      status:              'Estado',
      motivoBaja:          'Motivo de baja',
      fechaBaja:           'Fecha de baja',
    },
    messages: {
      createSuccess: 'Usuario creado correctamente.',
      createError:   'Error al crear el usuario.',
      updateSuccess: 'Usuario actualizado correctamente.',
      updateError:   'Error al actualizar el usuario.',
      noUsers:       'No hay usuarios registrados aún.',
      noSupervisors: 'No hay supervisores disponibles.',
    },
    deactivate:   'Desactivar',
    activate:     'Activar',
    confirmDeactivate: '¿Desactivar este usuario?',
    password: {
      tooShort:         'La contraseña debe tener al menos 8 caracteres.',
      missingNumber:    'La contraseña debe incluir al menos un número.',
      missingUppercase: 'La contraseña debe incluir al menos una mayúscula.',
    },
    resetPassword: {
      action:        'Restablecer contraseña',
      title:         'Restablecer contraseña',
      description:   'El usuario podrá ingresar únicamente con esta contraseña nueva a partir de ahora.',
      passwordLabel: 'Contraseña nueva',
      confirm:       'Restablecer',
      success:       'Contraseña restablecida correctamente.',
      error:         'Error al restablecer la contraseña.',
    },
    bajaModal: {
      title:            'Dar de baja',
      motivoLabel:      'Motivo de la baja',
      motivoPlaceholder: 'Explicá el motivo de la baja.',
      motivoRequired:   'El motivo de la baja es requerido.',
      fechaLabel:       'Fecha de baja',
      fechaRequired:    'La fecha de baja es requerida.',
      confirm:          'Confirmar baja',
      success:          'Usuario dado de baja correctamente.',
      error:            'Error al dar de baja al usuario.',
    },
    activateSuccess: 'Usuario activado correctamente.',
    activateError:   'Error al activar el usuario.',
    errors: {
      userNotFound:         'El usuario no existe o ya no está disponible.',
      updateFailed:         'No se pudo actualizar el usuario. Intentá de nuevo.',
      cannotDeactivateSelf: 'No podés desactivar tu propia cuenta.',
      // FB-PI-11-B: el índice único de la migración 0022 hace imposibles dos
      // perfiles cuyo email difiera solo en mayúsculas o espacios.
      emailDuplicado:       'Ya existe un usuario con ese correo electrónico (sin distinguir mayúsculas).',
    },
  },

  miPerfil: {
    title:    'Mi Perfil',
    subtitle: 'Tus datos personales y documentos',
    sectionDatos: 'Datos personales',
    sectionDocumentos: 'Documentos',
    fields: {
      nombreCompleto: 'Nombre completo',
      email:         'Correo electrónico',
      telefono:      'Teléfono',
      cuit:          'CUIT',
      windaId:       'Winda ID',
      dni:           'DNI',
      fechaIngreso:  'Fecha de ingreso',
      rol:           'Rol',
      estado:        'Estado',
      supervisor:    'Supervisor',
    },
    adminFields: {
      entrevistaTecnica: 'Entrevista técnica',
      tiposTrabajoTitle: 'Tipos de trabajo habilitados',
      tiposTrabajo: {
        aerogeneradores:     'Aerogeneradores',
        palas_eolicas:       'Palas eólicas',
        trabajo_en_altura:   'Trabajo en altura',
        escalada_industrial: 'Escalada industrial',
        inspeccion_visual:   'Inspección visual',
      },
    },
    placeholders: {
      nombreCompleto: 'Nombre y apellido',
      telefono:  'Ej: +54 9 261 000-0000',
      cuit:      'Ej: 20-12345678-9',
      windaId:   'ID Winda',
      dni:       'Número de DNI',
    },
    readOnly: 'Solo lectura. Los cambios deben solicitarse a Administración.',
    editButton: 'Editar perfil',
    saveButton: 'Guardar cambios',
    messages: {
      updateSuccess: 'Perfil actualizado correctamente.',
      updateError:   'Error al actualizar el perfil.',
      noValue:       'Sin datos',
    },
  },

  documentos: {
    sectionTitle:  'Documentos',
    uploadButton:  'Subir documento',
    previewButton: 'Ver documento',
    noDocuments:   'No hay documentos cargados aún.',
    uploadModalTitle: 'Subir documento',
    fields: {
      tipo:             'Tipo de documento',
      certificadoTipo:  'Tipo de certificado',
      otrosTexto:       'Descripción del certificado',
      fechaVencimiento: 'Fecha de vencimiento',
      archivo:          'Archivo',
    },
    placeholders: {
      tipo:            'Seleccioná el tipo',
      certificadoTipo: 'Seleccioná el tipo de certificado',
      otrosTexto:      'Describí el certificado (máx. 80 caracteres)',
      fechaVencimiento:'Fecha de vencimiento',
    },
    tipos: {
      dni:           'DNI',
      licencia:      'Licencia de conducir',
      foto_carnet:   'Foto carnet 4×4',
      certificado:   'Certificado',
      estudio_medico:'Estudio médico',
    },
    certificadoTipos: {
      gwo:               'GWO',
      cursos_elevadores: 'Cursos elevadores',
      espacio_confinado: 'Espacio confinado',
      manejo_defensivo:  'Manejo defensivo',
      cursos_vestas:     'Cursos Vestas',
      otros:             'Otros',
    },
    hints: {
      otrosTexto:       'Requerido cuando el tipo es "Otros".',
      fechaVencimiento: 'Requerida para certificados con vencimiento.',
      archivo:          'PDF o imagen, máximo 10 MB.',
      purgatorio:       'Tu documento será revisado por Administración.',
    },
    messages: {
      uploadSuccess: 'Documento enviado. Quedará Pendiente hasta que Administración lo apruebe.',
      uploadError:   'Error al subir el documento.',
      uploadingMsg:  'Subiendo documento...',
    },
    table: {
      tipo:             'Tipo',
      archivo:          'Archivo',
      vencimiento:      'Vencimiento',
      estado:           'Estado',
      fecha:            'Fecha de carga',
      acciones:         'Acciones',
    },
    statusBanner: {
      pendiente: 'Pendiente de aprobación.',
      aprobado:  'Documento aprobado.',
      rechazado: 'Documento rechazado.',
    },
    rechazadoBanner: 'Motivo del rechazo',
    archivoEliminado: 'Archivo eliminado por retención (30 días)',
    errors: {
      archivoRequerido:         'Seleccioná un archivo para subir.',
      tipoNoPermitido:          'Tipo de documento no permitido.',
      certificadoTipoRequerido: 'Seleccioná el tipo de certificado.',
      descripcionRequerida:     'La descripción del certificado es requerida.',
      descripcionMaxima:        'La descripción no puede superar los 80 caracteres.',
      archivoDemasiadoGrande:   'El archivo excede el límite de 10 MB.',
      tipoArchivoNoPermitido:   'Tipo de archivo no permitido:',
      urlNoDisponible:          'No se pudo generar la URL de acceso.',
      cargaError:               'No se pudieron cargar los documentos. Intentá recargar la página.',
    },
  },

  procedimientos: {
    newButton:      'Nuevo procedimiento',
    editButton:     'Editar',
    archiveButton:  'Archivar',
    restoreButton:  'Restaurar',
    backToList:     'Volver a Procedimientos',
    openFile:       'Abrir archivo',
    downloadFile:   'Descargar archivo',
    nuevoBadge:     'Nuevo',
    archivadoBadge: 'Archivado',
    search: {
      placeholder:      'Buscar por título o categoría...',
      categoriaLabel:   'Categoría',
      categoriaTodas:   'Todas las categorías',
      mostrarArchivados:'Mostrar archivados',
    },
    emptyState: {
      adminSinResultados:  'No se encontraron procedimientos con ese filtro.',
      adminSinNinguno:     'Todavía no cargaste ningún procedimiento.',
      noAdminSinResultados:'No se encontraron procedimientos con ese filtro.',
      noAdminSinNinguno:   'Todavía no hay procedimientos publicados.',
    },
    table: {
      titulo:        'Título',
      categoria:     'Categoría',
      actualizado:   'Última actualización',
      actualizadoPor:'Actualizado por',
      acciones:      'Acciones',
    },
    view: {
      categoriaLabel:    'Categoría',
      actualizadoLabel:  'Última actualización',
      actualizadoPorLabel: 'Actualizado por',
      sinCategoria:      'Sin categoría',
      archivadoAviso:    'Este procedimiento está archivado. Los empleados y supervisores no lo ven.',
      cargandoArchivo:   'Generando el enlace de descarga...',
      archivoNoDisponible: 'No se pudo generar el enlace de descarga.',
    },
    form: {
      crearTitle:     'Nuevo procedimiento',
      editarTitle:    'Editar procedimiento',
      titulo:         'Título',
      tituloPlaceholder: 'Ej. Protocolo de izaje de pala',
      categoria:      'Categoría',
      categoriaPlaceholder: 'Ej. Seguridad (elegí una existente o escribí una nueva)',
      tipoContenido:  'Contenido',
      tipoTexto:      'Texto',
      tipoArchivo:    'Archivo',
      tipoContenidoHint: 'Elegí una sola forma: texto escrito en la app, o un archivo. No las dos.',
      contenidoTexto: 'Contenido',
      archivo:        'Archivo',
      archivoHintNuevo:    'PDF, Word (.doc/.docx) o texto plano (.txt), máximo 10 MB.',
      archivoHintExistente:'Dejalo vacío para conservar el archivo actual.',
      guardar:        'Guardar',
      guardando:      'Guardando...',
      cancelar:       'Cancelar',
    },
    markdownToolbar: {
      negrita: 'Negrita',
      lista:   'Lista',
      titulo:  'Título',
    },
    confirmArchivar: {
      title:   '¿Archivar este procedimiento?',
      message: 'Va a dejar de verse para Supervisores y Empleados. No se borra: lo podés restaurar cuando quieras.',
      confirm: 'Archivar',
    },
    confirmRestaurar: {
      title:   '¿Restaurar este procedimiento?',
      message: 'Va a volver a verse para todos los roles.',
      confirm: 'Restaurar',
    },
    messages: {
      creado:      'Procedimiento creado.',
      actualizado: 'Procedimiento actualizado.',
      archivado:   'Procedimiento archivado.',
      restaurado:  'Procedimiento restaurado.',
    },
    errors: {
      tituloRequerido:        'El título es requerido.',
      contenidoExclusivo:     'Elegí texto o archivo, no los dos.',
      contenidoRequerido:     'Cargá el contenido en texto o subí un archivo.',
      archivoRequerido:       'Seleccioná un archivo para subir.',
      archivoDemasiadoGrande: 'El archivo excede el límite de 10 MB.',
      tipoArchivoNoPermitido: 'Tipo de archivo no permitido:',
      urlNoDisponible:        'No se pudo generar la URL de acceso.',
      cargaError:             'No se pudieron cargar los procedimientos. Intentá recargar la página.',
      noEncontrado:           'El procedimiento no existe o fue eliminado.',
      generic:                'No se pudo completar la operación. Intentá de nuevo.',
    },
  },

  solicitudAusencia: {
    formTitle:    'Solicitud de Ausencia',
    submitButton: 'Enviar solicitud',
    fields: {
      motivo:      'Motivo',
      fechaInicio: 'Fecha de inicio',
      fechaFin:    'Fecha de fin',
      motivoOtros: 'Detalle del motivo',
      nota:        'Nota',
    },
    placeholders: {
      motivo:      'Seleccioná el motivo',
      motivoOtros: 'Describí el motivo (máx. 80 caracteres)',
      nota:        'Agregá una aclaración (opcional).',
    },
    messages: {
      success:      'Solicitud enviada. Quedará Pendiente hasta que Administración la apruebe.',
      // FB-ADJ-01: éxito distinto para admin — su envío se auto-aprueba, no
      // pasa por la bandeja de Aprobaciones.
      successAdmin: 'Solicitud enviada y aprobada automáticamente.',
      enviando:     'Enviando...',
    },
    // FB-ADJ-01: diálogo de confirmación previo al envío, solo para admin
    // (su solicitud se auto-aprueba, no pasa por revisión).
    adminConfirm: {
      title:   'Confirmar envío',
      message: 'Como administrador, esta solicitud se aprueba automáticamente y no pasa por revisión. ¿Confirmás el envío?',
      confirm: 'Confirmar envío',
      cancel:  'Cancelar',
    },
    errors: {
      motivoRequerido:          'Seleccioná un motivo.',
      fechaRequerida:           'Seleccioná las fechas de inicio y fin.',
      fechaFinAnteriorAInicio:  'La fecha de fin no puede ser anterior a la fecha de inicio.',
      fechaRetroactiva:         'No podés solicitar una ausencia que empiece antes de hoy.',
      motivoOtrosRequerido:     'Describí el motivo.',
      motivoOtrosMaximo:        'El detalle no puede superar los 80 caracteres.',
      pendienteDuplicada:       'Ya tenés una solicitud pendiente que se superpone con estas fechas. Resolvela antes de pedir otra.',
    },
    listTitle:     'Mis solicitudes',
    noSolicitudes: 'No hay solicitudes registradas aún.',
    table: {
      motivo:         'Motivo',
      fecha:          'Fecha',
      nota:           'Nota',
      estado:         'Estado',
      motivoRechazo:  'Motivo del rechazo',
      postAprobacion: 'Cambio posterior',
    },
    estados: {
      pendiente: 'Pendiente',
      aprobado:  'Aprobada',
      rechazado: 'Rechazada',
    },
    saldo: {
      title:           'Días de trámite',
      restantesPrefix: 'Te quedan',
      restantesSufijo: 'días de trámite este año.',
      sinDisponibles:  'No te quedan días de trámite disponibles este año.',
      excedido:        'Superaste el tope de días de trámite de este año.',
      fechasTitle:     'Fechas usadas este año',
      sinFechas:       'Todavía no usaste ningún día de trámite este año.',
    },
  },

  solicitudPasaje: {
    formTitle:    'Solicitud de Pasaje',
    submitButton: 'Enviar solicitud',
    fields: {
      empleado:    'Empleado',
      motivoViaje: 'Motivo del viaje',
      origen:      'Origen',
      destino:     'Destino',
      diasViaje:   'Días de viaje',
      nota:        'Nota',
    },
    placeholders: {
      empleado:    'Seleccioná un integrante de tu equipo',
      motivoViaje: 'Seleccioná el motivo',
      origen:      'Ej: Mendoza',
      destino:     'Ej: Bahía Blanca',
      nota:        'Agregá una aclaración (opcional).',
    },
    motivos: {
      inicio_franco:      'Inicio de franco',
      fin_franco:         'Fin de franco',
      traslado_proyectos: 'Traslado entre proyectos',
    },
    diasViaje: {
      agregarDia: 'Agregar día',
      quitarDia:  'Quitar',
    },
    messages: {
      success:      'Solicitud enviada. Quedará Pendiente hasta que Administración la apruebe.',
      // FB-ADJ-01: éxito distinto para admin — su envío se auto-aprueba, no
      // pasa por la bandeja de Aprobaciones.
      successAdmin: 'Solicitud enviada y aprobada automáticamente.',
      enviando:     'Enviando...',
    },
    // FB-ADJ-01: diálogo de confirmación previo al envío, solo para admin
    // (su solicitud se auto-aprueba, no pasa por revisión).
    adminConfirm: {
      title:   'Confirmar envío',
      message: 'Como administrador, esta solicitud se aprueba automáticamente y no pasa por revisión. ¿Confirmás el envío?',
      confirm: 'Confirmar envío',
      cancel:  'Cancelar',
    },
    errors: {
      empleadoRequerido:     'Seleccioná para quién es el pasaje.',
      empleadoFueraDeEquipo: 'Solo podés pedir pasajes para vos o para tu equipo.',
      motivoRequerido:       'Seleccioná el motivo del viaje.',
      origenRequerido:       'Ingresá el origen.',
      destinoRequerido:      'Ingresá el destino.',
      diasRequeridos:        'Agregá al menos un día de viaje.',
      diaRetroactivo:        'No podés solicitar un pasaje con un día de viaje anterior a hoy.',
    },
    listTitle:     'Mis solicitudes',
    noSolicitudes: 'No hay solicitudes registradas aún.',
    table: {
      empleado:       'Empleado',
      motivo:         'Motivo',
      recorrido:      'Recorrido',
      dias:           'Días de viaje',
      nota:           'Nota',
      estado:         'Estado',
      motivoRechazo:  'Motivo del rechazo',
      postAprobacion: 'Cambio posterior',
    },
    estados: {
      pendiente: 'Pendiente',
      aprobado:  'Aprobada',
      rechazado: 'Rechazada',
    },
    // FB-F4-15: "Mis solicitudes" ahora incluye pasajes donde el usuario es
    // solicitante O empleado viajero — dos perspectivas posibles sobre la
    // misma fila, así que el label de "para quién" cambia según quién sea.
    detalle: {
      paraLabel:     'Para',
      pedidoPorLabel:'Pedido por',
    },
  },

  adminEmpleado: {
    selectorTitle:       'Administrar perfil de empleado',
    selectorPlaceholder: 'Buscar por nombre o correo…',
    selectorHint:        'Ingresá al menos 2 caracteres.',
    noResults:           'Sin resultados.',
    pageTitle:           'Perfil de empleado',
    backButton:          'Volver a Mi Perfil',
    adminUploadHint:     'Como administrador, el archivo quedará aprobado directamente.',
  },

  aprobaciones: {
    title:    'Aprobaciones',
    subtitle: 'Bandeja única de solicitudes pendientes',
    noItems:  'No hay solicitudes pendientes.',
    table: {
      tipo:       'Tipo',
      usuario:    'Usuario',
      detalle:    'Detalle',
      fecha:      'Fecha',
      estado:     'Estado',
      acciones:   'Acciones',
    },
    tipos: {
      documento:  'Documento',
      pasaje:     'Pasaje',
      ausencia:   'Ausencia',
    },
    actions: {
      aprobar:   'Aprobar',
      rechazar:  'Rechazar',
      ver:       'Ver',
    },
    rejectModal: {
      title:       'Rechazar solicitud',
      motivoLabel: 'Motivo del rechazo',
      motivoPlaceholder: 'Explicá el motivo para que el usuario pueda corregir y reenviar.',
      motivoRequired: 'El motivo del rechazo es requerido.',
      confirm:     'Confirmar rechazo',
    },
    messages: {
      approveSuccess:     'Solicitud aprobada.',
      approveError:       'Error al aprobar la solicitud.',
      rejectSuccess:      'Solicitud rechazada.',
      rejectError:        'Error al rechazar la solicitud.',
      alreadyResolved:    'Esta solicitud ya fue resuelta.',
      resolvedEmailFailed: 'Resuelto; no se pudo enviar el mail.',
    },
    badgeSaldo: {
      usado:   'Usó',
      de:      'de',
      excede:  'excede',
      error:   'No se pudo calcular el saldo.',
    },
    sobrescritura: {
      aviso:       'Al aprobar, estos días se sobrescriben a período fuera de trabajo.',
      avisoPasaje: 'Al aprobar, estos días se sobrescriben a en viaje.',
      error:       'No se pudo calcular la previsualización de sobrescritura.',
    },
    detallePasaje: {
      paraLabel: 'Para',
    },
    verAprobadas: 'Ver aprobadas',
  },

  aprobadas: {
    title:    'Solicitudes Aprobadas',
    subtitle: 'Ausencias y pasajes ya aprobados. Cancelalos o editá sus fechas si hace falta.',
    noItems:  'No hay solicitudes aprobadas.',
    volverAprobaciones: 'Volver a Aprobaciones',
    filtro: {
      label:       'Filtrar por empleado',
      placeholder: 'Todos los empleados',
    },
    table: {
      tipo:      'Tipo',
      empleado:  'Empleado',
      detalle:   'Detalle',
      fecha:     'Fecha',
      marca:     'Cambio post-aprobación',
      acciones:  'Acciones',
    },
    marca: {
      comentarioLabel: 'Motivo',
      fechaLabel:       'Fecha del cambio',
      sinCambios:       '—',
    },
    actions: {
      cancelar:     'Cancelar',
      editarFechas: 'Editar fechas',
    },
    cancelModal: {
      title:               'Cancelar solicitud aprobada',
      warning:              'Se van a liberar los días asignados en el calendario del empleado. Esta acción no se puede deshacer.',
      comentarioLabel:      'Motivo del cambio',
      comentarioPlaceholder:'Explicá por qué se cancela esta solicitud — el empleado lo va a ver.',
      comentarioRequired:   'El comentario es obligatorio.',
      confirm:              'Confirmar cancelación',
    },
    editModal: {
      title:                 'Editar fechas',
      fechaInicioLabel:      'Nueva fecha de inicio',
      fechaFinLabel:         'Nueva fecha de fin',
      diaLabel:              'Día de viaje',
      agregarDia:            'Agregar día',
      quitarDia:             'Quitar',
      comentarioLabel:       'Motivo del cambio',
      comentarioPlaceholder: 'Explicá por qué se editan estas fechas — el empleado lo va a ver.',
      comentarioRequired:    'El comentario es obligatorio.',
      confirm:               'Confirmar edición',
      previewLoading:        'Calculando previsualización…',
      previewButton:         'Previsualizar sobrescritura',
    },
    errors: {
      comentarioRequerido:      'El comentario es obligatorio.',
      fechaRequerida:            'Seleccioná las fechas nuevas.',
      fechaFinAnteriorAInicio:   'La fecha de fin no puede ser anterior a la fecha de inicio.',
      fechaRetroactiva:          'No podés elegir una fecha anterior a hoy.',
      diasRequeridos:            'Agregá al menos un día de viaje.',
      diaRetroactivo:            'No podés elegir un día de viaje anterior a hoy.',
      lifoBloqueo:               'No se puede completar esta acción: hay solicitudes aprobadas más recientes que se superponen en fechas y hay que resolver primero:',
      yaNoVigente:               'Esta solicitud ya no está vigente — puede haber sido cancelada o editada por otro admin. Recargá la página.',
      generic:                   'Error al procesar el cambio.',
    },
    messages: {
      cancelSuccess: 'Solicitud cancelada.',
      editSuccess:   'Fechas actualizadas.',
      emailFailed:   'Hecho; no se pudo enviar el mail al empleado.',
    },
    sobrescritura: {
      aviso: 'Estos días ya tienen una fila en el calendario del empleado — se van a sobrescribir.',
      error: 'No se pudo calcular la previsualización de sobrescritura.',
      vacio: 'Ninguno de los días nuevos tiene fila cargada en el calendario todavía.',
    },
  },

  emails: {
    documentoRechazado: {
      subject:     'Tu documento fue rechazado — First Blades',
      saludo:      'Hola',
      intro:       'Tu documento fue revisado por Administración y fue rechazado.',
      tipoLabel:   'Documento',
      motivoLabel: 'Motivo del rechazo',
      accion:      'Podés corregirlo y volver a enviarlo desde el portal, en la sección Mi Perfil.',
      firma:       'Equipo First Blades',
    },
    vencimientoEmpleado: {
      subject:          'Tu documento está por vencer — First Blades',
      saludo:           'Hola',
      intro:            'Uno de tus documentos está por vencer.',
      tipoLabel:        'Documento',
      vencimientoLabel: 'Fecha de vencimiento',
      diasLabel:        'Días restantes',
      accion:           'Actualizalo desde el portal, en la sección Mi Perfil, antes de que venza.',
      firma:            'Equipo First Blades',
    },
    vencimientoAdmin: {
      subject:          'Documento de un empleado por vencer — First Blades',
      intro:            'El documento de un integrante del equipo está por vencer.',
      empleadoLabel:    'Empleado',
      tipoLabel:        'Documento',
      vencimientoLabel: 'Fecha de vencimiento',
      diasLabel:        'Días restantes',
      firma:            'Equipo First Blades',
    },
    alertaFranco: {
      subject:       'Alerta de descanso de un empleado — First Blades',
      intro:         'Un empleado alcanzó una alerta de descanso en el Calendario de rotaciones.',
      empleadoLabel: 'Empleado',
      alertaLabel:   'Alerta',
      accion:        'Podés ver el detalle en el Calendario del portal, sección Alertas de descanso.',
      firma:         'Equipo First Blades',
    },
    ausenciaAprobada: {
      subject:      'Tu solicitud de ausencia fue aprobada — First Blades',
      saludo:       'Hola',
      intro:        'Tu solicitud de ausencia fue revisada por Administración y fue aprobada.',
      motivoLabel:  'Motivo',
      periodoLabel: 'Período',
      accion:       'Ya podés verla reflejada en el Calendario del portal.',
      firma:        'Equipo First Blades',
    },
    ausenciaRechazada: {
      subject:            'Tu solicitud de ausencia fue rechazada — First Blades',
      saludo:             'Hola',
      intro:              'Tu solicitud de ausencia fue revisada por Administración y fue rechazada.',
      motivoLabel:        'Motivo',
      periodoLabel:       'Período',
      motivoRechazoLabel: 'Motivo del rechazo',
      accion:             'Podés volver a enviarla desde el portal, en la sección Solicitud de Ausencia.',
      firma:              'Equipo First Blades',
    },
    pasajeAprobado: {
      subject:        'Tu solicitud de pasaje fue aprobada — First Blades',
      saludo:         'Hola',
      intro:          'Tu solicitud de pasaje fue revisada por Administración y fue aprobada.',
      motivoLabel:    'Motivo',
      recorridoLabel: 'Recorrido',
      diasLabel:      'Días de viaje',
      accion:         'Ya podés verlo reflejado en el Calendario del portal.',
      firma:          'Equipo First Blades',
    },
    pasajeRechazado: {
      subject:            'Tu solicitud de pasaje fue rechazada — First Blades',
      saludo:             'Hola',
      intro:              'Tu solicitud de pasaje fue revisada por Administración y fue rechazada.',
      motivoLabel:        'Motivo',
      recorridoLabel:     'Recorrido',
      diasLabel:          'Días de viaje',
      motivoRechazoLabel: 'Motivo del rechazo',
      accion:             'Podés volver a enviarla desde el portal, en la sección Solicitud de Pasaje.',
      firma:              'Equipo First Blades',
    },
    ausenciaCancelada: {
      subject:        'Tu solicitud de ausencia fue cancelada — First Blades',
      saludo:         'Hola',
      intro:          'Una solicitud de ausencia tuya, ya aprobada, fue cancelada por Administración.',
      motivoLabel:    'Motivo',
      periodoLabel:   'Período cancelado',
      comentarioLabel:'Por qué',
      accion:         'Podés ver el detalle en la sección Solicitud de Ausencia del portal.',
      firma:          'Equipo First Blades',
    },
    ausenciaEditada: {
      subject:          'Se editaron las fechas de tu ausencia — First Blades',
      saludo:           'Hola',
      intro:            'Una solicitud de ausencia tuya, ya aprobada, tuvo sus fechas editadas por Administración.',
      motivoLabel:      'Motivo',
      periodoAnteriorLabel: 'Fechas anteriores',
      periodoNuevoLabel:    'Fechas nuevas',
      comentarioLabel:  'Por qué',
      accion:           'Podés ver el detalle en la sección Solicitud de Ausencia del portal.',
      firma:            'Equipo First Blades',
    },
    pasajeCancelado: {
      subject:        'Tu solicitud de pasaje fue cancelada — First Blades',
      saludo:         'Hola',
      intro:          'Una solicitud de pasaje tuya, ya aprobada, fue cancelada por Administración.',
      motivoLabel:    'Motivo',
      recorridoLabel: 'Recorrido',
      diasLabel:      'Días cancelados',
      comentarioLabel:'Por qué',
      accion:         'Podés ver el detalle en la sección Solicitud de Pasaje del portal.',
      firma:          'Equipo First Blades',
    },
    pasajeEditado: {
      subject:            'Se editaron los días de tu pasaje — First Blades',
      saludo:             'Hola',
      intro:              'Una solicitud de pasaje tuya, ya aprobada, tuvo sus días editados por Administración.',
      motivoLabel:        'Motivo',
      recorridoLabel:     'Recorrido',
      diasAnterioresLabel:'Días anteriores',
      diasNuevosLabel:    'Días nuevos',
      comentarioLabel:    'Por qué',
      accion:             'Podés ver el detalle en la sección Solicitud de Pasaje del portal.',
      firma:              'Equipo First Blades',
    },
  },

  errors: {
    unauthorized:   'No tenés permiso para acceder a esta sección.',
    sessionExpired: 'Tu sesión expiró. Iniciá sesión nuevamente.',
    generic:        'Ocurrió un error inesperado. Intentá nuevamente.',
    notFound:       'Página no encontrada.',
  },

  topbar: {
    notifications: 'Notificaciones',
    userMenu:      'Menú de usuario',
    menuButton:    'Menú',
    // FB-PI-01: aria-label de la campanita del admin (link a Aprobaciones).
    // Se arma como "<prefijo> <n> <sufijo>"; con 0, el texto sin cantidad.
    aprobacionesPendientesPrefijo:  'Notificaciones:',
    aprobacionesPendientesSufijoUna: 'aprobación pendiente',
    aprobacionesPendientesSufijo:   'aprobaciones pendientes',
    aprobacionesSinPendientes:      'Notificaciones: sin aprobaciones pendientes',
    // Tope visual del badge: hasta 99 se muestra el número exacto.
    aprobacionesPendientesTope:     '99+',
  },

  miEquipo: {
    title:      'Mi Equipo',
    subtitle:   'Perfiles de los técnicos de tu equipo',
    noMiembros: 'No hay miembros en tu equipo.',
    table: {
      nombre:   'Nombre',
      email:    'Correo electrónico',
      telefono: 'Teléfono',
      estado:   'Estado',
      rol:      'Rol',
    },
    detalle: {
      backToList:   'Volver a Mi Equipo',
      noEncontrado: 'Miembro no encontrado.',
      sinDatos:     '—',
    },
    campos: {
      nombre:   'Nombre',
      email:    'Correo electrónico',
      telefono: 'Teléfono',
      estado:   'Estado',
      rol:      'Rol',
    },
  },

  equipo: {
    title:   'Equipo',
    subtitle: 'Estado documental de todos los perfiles',
    search:   'Buscar por nombre o correo…',
    filtroEstado: 'Estado',
    todoEstado:   'Todos los estados',
    noPerfiles:   'No hay perfiles registrados.',
    table: {
      nombre:       'Nombre',
      email:        'Correo electrónico',
      rol:          'Rol',
      supervisor:   'Supervisor',
      estado:       'Estado',
      docVencidos:  'Vencidos',
      docPorVencer: 'Por vencer',
    },
    proximosAVencer: {
      title:    'Próximos a vencer',
      subtitle: 'Documentos vencidos o que vencen en los próximos 30 días',
      noItems:  'No hay documentos próximos a vencer.',
      table: {
        empleado:      'Empleado',
        documento:     'Documento',
        vencimiento:   'Vencimiento',
        diasRestantes: 'Días restantes',
      },
    },
    diasHoy:   'Hoy',
    diasHace:  'Hace',
    diasLabel: 'días',
    diaLabel:  'día',
  },

  calendario: {
    title:    'Calendario',
    subtitle: 'Calendario de rotación',
    meses: [
      'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
      'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
    ],
    nav: {
      mesAnterior: 'Mes anterior',
      mesSiguiente: 'Mes siguiente',
      hoy:          'Hoy',
    },
    table: {
      empleado: 'Empleado',
    },
    leyenda: {
      title:      'Referencias',
      sinCargar:  'Sin asignar',
      estimado:   'Planificado',
    },
    noEmpleados: 'No hay empleados activos para mostrar en el roster.',
    modal: {
      title:  'Editar día',
      guardar: 'Guardar',
      fields: {
        empleado:  'Empleado',
        fecha:     'Fecha',
        estado:    'Estado',
        motivo:    'Motivo',
        motivoOtros: 'Detalle del motivo',
        estimado:  'Planificado (a futuro)',
      },
      placeholders: {
        motivo:      'Seleccioná el motivo',
        motivoOtros: 'Describí el motivo (máx. 80 caracteres)',
      },
      hints: {
        estimado: 'Los días planificados se muestran en tono más claro hasta 7 días antes de la fecha.',
      },
    },
    motivos: {
      vacaciones:      'Vacaciones',
      licencia_medica: 'Licencia médica',
      dia_tramite:     'Día de trámite',
      matrimonio:      'Matrimonio',
      fallecimiento:   'Fallecimiento',
      otros:           'Otros',
    },
    range: {
      modal: {
        title:   'Aplicar a varios días',
        guardar: 'Aplicar',
        cerrar:  'Cerrar',
        rango:   'Rango',
      },
      seleccion: {
        diaSingular: 'día seleccionado',
        diasPlural:  'días seleccionados',
        anclaHint:   'Elegí el último día del rango con shift-click, o presioná Esc para cancelar.',
      },
      resultado: {
        aplicaronPrefijo: 'Se aplicaron',
        de:               'de',
        diaSingular:      'día',
        diasPlural:       'días',
        fallaronTitulo:   'No se pudieron aplicar estos días:',
      },
      errors: {
        diaTramiteNoDisponible:
          'El motivo "Día de trámite" no está disponible acá: se gestiona por Solicitud de Ausencia con aprobación del admin.',
        permisoDenegado: 'No tenés permiso para modificar este día.',
        diaFallidoGenerico: 'No se pudo guardar este día.',
      },
    },
    dashboard: {
      title:    'Resumen de ausencias del mes',
      subtitle: 'Días por motivo, por empleado, en el mes visible.',
      total:    'Total',
    },
    alertasFranco: {
      title:      'Alertas de descanso',
      subtitle:   'Empleados con muchos días trabajados sin descanso o con franco prolongado.',
      sinAlertas: 'Sin alertas de descanso.',
      table: {
        empleado: 'Empleado',
        tipo:     'Alerta',
      },
      tipos: {
        sin_franco:       'días sin descanso',
        franco_excedido:  'días de franco prolongado',
      },
    },
    saldoDiasTramite: {
      title:        'Saldo de días de trámite',
      subtitle:     'Días de trámite usados y disponibles este año, por empleado.',
      sinEmpleados: 'No hay empleados activos para mostrar.',
      table: {
        empleado:  'Empleado',
        usados:    'Usados',
        restantes: 'Restantes',
        estado:    'Estado',
      },
      estados: {
        disponible: 'Disponible',
        excedido:   'Excedido',
      },
    },
    filtroEmpleado: {
      label:         'Filtrar por empleado',
      todos:         'Todos los empleados',
      seleccionado:  'seleccionado',
      seleccionados: 'seleccionados',
      limpiar:       'Limpiar filtro',
    },
    errors: {
      motivoRequerido:      'Seleccioná un motivo para "Fuera del trabajo".',
      motivoOtrosRequerido: 'Describí el motivo cuando seleccionás "Otros".',
      motivoOtrosMaximo:    'El detalle del motivo no puede superar los 80 caracteres.',
    },
    messages: {
      upsertSuccess: 'Día actualizado correctamente.',
      upsertError:   'Error al actualizar el día.',
      loadError:     'No se pudo cargar el roster del mes.',
    },
    // FB-PI-04: export del calendario a Excel (admin). Las etiquetas de
    // estado/motivo de acá son las que lee el import (FB-PI-05) — el mapeo
    // etiqueta↔enum vive en lib/rotation/calendario-excel-mapping.ts.
    excel: {
      panel: {
        title:    'Exportar a Excel',
        subtitle: 'Descargá el calendario de los empleados y supervisores activos para completarlo fuera de la app.',
        desde:    'Desde',
        hasta:    'Hasta',
        exportar: 'Exportar',
        exportado: 'Archivo descargado.',
      },
      // Nombres técnicos de las columnas: son la clave que lee el import, no
      // se traducen ni se embellecen.
      columnas: {
        email:        'email',
        nombre:       'nombre',
        fecha:        'fecha',
        estado:       'estado',
        motivo:       'motivo',
        motivo_otros: 'motivo_otros',
        notas:        'notas',
      },
      hojas: {
        calendario: 'Calendario',
        referencia: 'Referencia',
      },
      // Las etiquetas de estado NO viven acá: salen de copy.status, las mismas
      // que ve el admin en la grilla (FB-PI-04-B). Los motivos salen de
      // copy.calendario.motivos. Ver lib/rotation/calendario-excel-mapping.ts.
      validacion: {
        estadoTitulo:  'Estado inválido',
        estadoMensaje: 'Elegí un estado de la lista o dejá la celda vacía (día sin asignar).',
        motivoTitulo:  'Motivo inválido',
        // Se completa con la etiqueta del estado (copy.status) al generar el archivo.
        motivoMensaje: 'Elegí un motivo de la lista. Solo se completa si el estado es',
        motivoOtrosTitulo:  'Detalle demasiado largo',
        motivoOtrosMensaje: 'El detalle del motivo no puede superar los 80 caracteres.',
      },
      referencia: {
        encabezados: {
          estado:      'estado',
          motivo:      'motivo',
          motivoOtros: 'motivo_otros',
          significado: 'Qué significa',
        },
        vacio:          '(vacío)',
        obligatorio:    'Obligatorio (máx. 80 caracteres)',
        noCorresponde:  'Debe quedar vacío',
        sinAsignar:     'Día sin asignar',
        diaAsignado:    'Día asignado',
        ausenciaPorMotivo: 'Ausencia por este motivo',
        // Se completa con la etiqueta del estado (copy.status) al generar el archivo.
        notaMotivo: 'El motivo solo se completa cuando el estado es',
        notas: [
          'Las columnas email, nombre y fecha están bloqueadas: no las modifiques.',
          'Una celda de estado vacía significa un día sin asignar.',
          'Los desplegables son una ayuda: el sistema vuelve a validar cada fila al importar el archivo.',
        ],
      },
      errors: {
        fechaInvalida:  'Ingresá un rango de fechas válido.',
        rangoInvertido: 'La fecha "Desde" no puede ser posterior a "Hasta".',
        rangoExcedido:  'El rango no puede superar los 366 días.',
        generacion:     'No se pudo generar el archivo. Intentá de nuevo.',
      },
      // FB-PI-11 — Import del calendario desde Excel (admin).
      importar: {
        panel: {
          title:        'Importar desde Excel',
          subtitle:     'Subí el archivo exportado y completado. Antes de guardar vas a ver qué cambia en el calendario.',
          archivo:      'Archivo (.xlsx)',
          previsualizar: 'Previsualizar',
          confirmar:    'Confirmar importación',
          cancelar:     'Cancelar',
        },
        preview: {
          titulo:       'Previsualización',
          archivoRango: 'Rango del archivo:',
          a:            'a',
          filas:        'filas',
          nadaEscrito:  'Todavía no se guardó nada. Revisá la previsualización y confirmá para aplicar los cambios.',
          resumen: {
            titulo:     'Resumen',
            crear:      'Días a crear',
            modificar:  'Días a modificar',
            sinCambios: 'Sin cambios',
            borrar:     'Días a borrar',
          },
          borrados: {
            titulo:     'Días que se van a borrar',
            // Tiene que estar dicho con todas las letras (PRD §4): vaciar una
            // celda es borrar un día, no "dejarlo como está".
            aviso:      'Una celda de estado vacía BORRA ese día del calendario. No lo deja como está: si el día tenía una asignación, se elimina.',
            ninguno:    'Ningún día se borra.',
          },
          pisados: {
            titulo:     'Días de solicitudes aprobadas que se van a pisar',
            aviso:      'Estos días hoy vienen de una solicitud aprobada. La importación los reemplaza; la solicitud no se modifica.',
            ninguno:    'La importación no pisa días de solicitudes aprobadas.',
            seBorra:    'Se borra',
            ausencia:   'Ausencia',
            pasaje:     'Pasaje',
          },
          saldo: {
            titulo:     'Impacto en el saldo de días de trámite',
            aviso:      'El saldo se calcula a partir del calendario: importar días de trámite los consume, aunque sean de fechas pasadas.',
            ninguno:    'La importación no cambia el saldo de días de trámite de nadie.',
            excedido:   'Excede el tope',
          },
          errores: {
            titulo:     'Errores de validación',
            aviso:      'Con errores no se puede confirmar. Corregí el archivo y volvé a subirlo.',
            ninguno:    'Sin errores de validación.',
            archivo:    'Archivo',
          },
          columnas: {
            fila:       'Fila',
            empleado:   'Empleado',
            fecha:      'Fecha',
            anio:       'Año',
            actual:     'Hoy',
            nuevo:      'Queda',
            solicitud:  'Solicitud',
            antes:      'Antes',
            despues:    'Después',
            tope:       'Tope',
            motivo:     'Motivo',
          },
        },
        exito: {
          titulo:     'Importación aplicada.',
          creadas:    'creados',
          modificadas: 'modificados',
          borradas:   'borrados',
          sinCambios: 'sin cambios',
        },
        errores: {
          // Archivo
          archivoRequerido:   'Elegí un archivo .xlsx.',
          archivoTipo:        'El archivo tiene que ser un .xlsx.',
          archivoGrande:      'El archivo supera 1 MB. Importá un rango más chico.',
          archivoIlegible:    'No se pudo leer el archivo. Verificá que sea un .xlsx exportado desde el portal.',
          sinHoja:            'El archivo no tiene la hoja "Calendario".',
          columnasFaltantes:  'Faltan columnas en la hoja "Calendario":',
          demasiadasFilas:    'El archivo tiene demasiadas filas para un calendario exportado.',
          sinFilas:           'El archivo no tiene filas para importar.',
          rangoExcedido:      'El archivo abarca más de 366 días',
          a:                  'a',
          // Filas
          emailVacio:         'Falta el email.',
          emailInexistente:   'El email no corresponde a ningún perfil del portal. El import no crea empleados.',
          emailAmbiguo:       'El email coincide con más de un perfil.',
          emailAdmin:         'El email es de un administrador: sus días se gestionan desde la app, no por Excel.',
          emailInactivo:      'El email es de un perfil inactivo.',
          fechaVacia:         'Falta la fecha.',
          fechaInvalida:      'La fecha no es válida (formato AAAA-MM-DD).',
          fechaFueraDeVentana: 'La fecha tiene que estar entre',
          y:                  'y',
          estadoInvalido:     'Estado inválido:',
          motivoInvalido:     'Motivo inválido:',
          motivoObligatorio:  'El motivo es obligatorio cuando el estado es "Fuera del trabajo".',
          motivoNoCorresponde: 'El motivo solo se completa cuando el estado es "Fuera del trabajo".',
          motivoSinEstado:    'Hay motivo o detalle pero el estado está vacío. Un estado vacío borra el día.',
          notasSinEstado:     'Hay notas pero el estado está vacío. Un estado vacío borra el día.',
          detalleObligatorio: 'El detalle (motivo_otros) es obligatorio cuando el motivo es "Otros".',
          detalleNoCorresponde: 'El detalle (motivo_otros) solo se completa cuando el motivo es "Otros".',
          detalleLargo:       'El detalle (motivo_otros) no puede superar los 80 caracteres.',
          duplicada:          'El mismo empleado y día aparece repetido. Ver también fila',
          // Confirmación
          conErrores:         'El archivo tiene errores de validación: no se puede confirmar.',
          sinPrevisualizar:   'Previsualizá el archivo antes de confirmar.',
          archivoDistinto:    'El archivo no es el mismo que se previsualizó. Volvé a previsualizar.',
          desactualizado:     'El calendario cambió desde la previsualización. Volvé a previsualizar antes de confirmar.',
          lectura:            'No se pudo leer el calendario actual. Intentá de nuevo.',
          escritura:          'No se pudo aplicar la importación. No se guardó ningún cambio.',
        },
      },
    },
  },

  pages: {
    dashboard: {
      title:       'Inicio',
      subtitle:    'Bienvenido al portal',
      welcome:     'Bienvenido al Portal First Blades',
      loggedAs:    'Ingresaste como',
      hint:        'Seleccioná una opción del menú lateral para comenzar.',
    },
    miPerfil: {
      title:    'Mi Perfil',
      subtitle: 'Tus datos personales y documentos',
    },
    equipo: {
      title:    'Equipo',
      subtitle: 'Estado documental de todos los perfiles',
    },
    miEquipo: {
      title:    'Mi Equipo',
      subtitle: 'Perfiles de los técnicos de tu equipo',
    },
    calendario: {
      title:    'Calendario',
      subtitle: 'Calendario de rotación',
    },
    solicitudPasaje: {
      title:    'Solicitud de Pasaje',
      subtitle: 'Gestioná tus pedidos de traslado',
    },
    solicitudAusencia: {
      title:    'Solicitud de Ausencia',
      subtitle: 'Gestioná tus pedidos de ausencia',
    },
    aprobaciones: {
      title:    'Aprobaciones',
      subtitle: 'Bandeja de solicitudes pendientes',
    },
    procedimientos: {
      title:    'Procedimientos / Políticas',
      subtitle: 'Documentos y normativa interna',
    },
    rendicionGastos: {
      title:    'Rendición de Gastos',
      subtitle: 'Acceso externo a Google Workspace',
    },
    gestionUsuarios: {
      title:    'Gestión de Usuarios',
      subtitle: 'Administrá los usuarios del portal',
    },
  },
} as const;
