// Todos los textos de UI en español (es-AR).
// Ningún componente debe tener strings hardcodeados; siempre importar desde acá.

export const copy = {
  general: {
    loading:   'Cargando...',
    error:     'Ocurrió un error',
    noData:    'Sin datos',
    save:      'Guardar',
    cancel:    'Cancelar',
    edit:      'Editar',
    delete:    'Eliminar',
    confirm:   'Confirmar',
    back:      'Volver',
    search:    'Buscar',
    filter:    'Filtrar',
    create:    'Crear',
    update:    'Actualizar',
    close:     'Cerrar',
    actions:   'Acciones',
    optional:  '(opcional)',
    required:  'Campo requerido',
    yes:       'Sí',
    no:        'No',
    logoAlt:   'Logo First Blades',
  },

  auth: {
    login: {
      welcome:             'Bienvenido',
      subtitle:            'Portal First Blades',
      brandTagline:        'Portal de operaciones de campo',
      email:               'Correo electrónico',
      emailPlaceholder:    'nombre@empresa.com',
      password:            'Contraseña',
      showPassword:        'Mostrar contraseña',
      hidePassword:        'Ocultar contraseña',
      submit:              'Ingresar',
      forgotPassword:      '¿Olvidaste tu contraseña?',
      secureAccess:        'Acceso seguro · First Blades',
      invalidCredentials:  'Correo o contraseña incorrectos.',
      genericError:        'Error al iniciar sesión. Intentá de nuevo.',
    },
    logout: 'Cerrar sesión',
  },

  nav: {
    miPerfil:         'Mi Perfil',
    equipo:           'Equipo',
    miEquipo:         'Mi Equipo',
    calendario:       'Calendario',
    solicitudPasaje:  'Solicitud de Pasaje',
    solicitudAusencia:'Solicitud de Ausencia',
    aprobaciones:     'Aprobaciones',
    procedimientos:   'Procedimientos / Políticas',
    rendicionGastos:  'Rendición de Gastos',
    // FB-ADJ-01: renombre de etiqueta únicamente — la ruta (/formularios) y
    // el contenido "próximamente" no cambian.
    formularios:      'Ingreso',
    gestionUsuarios:  'Gestión de Usuarios',
  },

  placeholder: {
    comingSoon:        'Próximamente',
    comingSoonDesc:    'Este módulo estará disponible próximamente.',
    externalLink:      'Accedé a tu Rendición de Gastos en Google Workspace.',
    externalBtn:       'Abrir en Google Workspace',
    externalPending:   'Enlace pendiente de configuración.',
  },

  status: {
    pendiente:             'Pendiente',
    aprobado:              'Aprobado',
    rechazado:             'Rechazado',
    activo:                'Activo',
    inactivo:              'Inactivo',
    trabajando:            'Trabajando',
    en_viaje:              'En viaje',
    en_franco:             'En franco',
    periodo_fuera_trabajo: 'Fuera del trabajo',
    editada:               'Editada',
    cancelada:             'Cancelada',
  },

  roles: {
    admin:      'Administrador',
    supervisor: 'Supervisor',
    empleado:   'Empleado',
  },

  purgatorio: {
    infoMessage:      'Tu solicitud será revisada por Administración.',
    pendingMessage:   'Tu solicitud está siendo revisada.',
    approvedMessage:  'Tu solicitud fue aprobada.',
    rejectedMessage:  'Tu solicitud fue rechazada.',
    motivo:           'Motivo del rechazo',
  },

  gestionUsuarios: {
    title:    'Gestión de Usuarios',
    subtitle: 'Administrá los usuarios del portal',
    createUser: 'Crear usuario',
    editUser:   'Editar usuario',
    passwordRequired: 'La contraseña inicial es requerida.',
    table: {
      nombre:      'Nombre',
      email:       'Correo electrónico',
      rol:         'Rol',
      supervisor:  'Supervisor',
      estado:      'Estado',
      ingreso:     'Ingreso',
      acciones:    'Acciones',
    },
    form: {
      nombre:              'Nombre completo',
      nombrePlaceholder:   'Nombre completo',
      email:               'Correo electrónico',
      rol:                 'Rol',
      supervisor:          'Supervisor',
      supervisorPlaceholder: 'Seleccioná un supervisor',
      supervisorHint:      'Solo visible si el rol es Empleado',
      password:            'Contraseña inicial',
      passwordHint:        'El usuario podrá cambiarla después del primer ingreso',
      status:              'Estado',
    },
    messages: {
      createSuccess: 'Usuario creado correctamente.',
      createError:   'Error al crear el usuario.',
      updateSuccess: 'Usuario actualizado correctamente.',
      updateError:   'Error al actualizar el usuario.',
      noUsers:       'No hay usuarios registrados aún.',
      noSupervisors: 'No hay supervisores disponibles.',
    },
    deactivate:   'Desactivar',
    activate:     'Activar',
    confirmDeactivate: '¿Desactivar este usuario?',
  },

  miPerfil: {
    title:    'Mi Perfil',
    subtitle: 'Tus datos personales y documentos',
    sectionDatos: 'Datos personales',
    sectionDocumentos: 'Documentos',
    fields: {
      nombreCompleto: 'Nombre completo',
      email:         'Correo electrónico',
      telefono:      'Teléfono',
      cuit:          'CUIT',
      windaId:       'Winda ID',
      dni:           'DNI',
      fechaIngreso:  'Fecha de ingreso',
      rol:           'Rol',
      estado:        'Estado',
      supervisor:    'Supervisor',
    },
    adminFields: {
      entrevistaTecnica: 'Entrevista técnica',
      tiposTrabajoTitle: 'Tipos de trabajo habilitados',
      tiposTrabajo: {
        aerogeneradores:     'Aerogeneradores',
        palas_eolicas:       'Palas eólicas',
        trabajo_en_altura:   'Trabajo en altura',
        escalada_industrial: 'Escalada industrial',
        inspeccion_visual:   'Inspección visual',
      },
    },
    placeholders: {
      nombreCompleto: 'Nombre y apellido',
      telefono:  'Ej: +54 9 261 000-0000',
      cuit:      'Ej: 20-12345678-9',
      windaId:   'ID Winda',
      dni:       'Número de DNI',
    },
    readOnly: 'Solo lectura. Los cambios deben solicitarse a Administración.',
    editButton: 'Editar perfil',
    saveButton: 'Guardar cambios',
    messages: {
      updateSuccess: 'Perfil actualizado correctamente.',
      updateError:   'Error al actualizar el perfil.',
      noValue:       'Sin datos',
    },
  },

  documentos: {
    sectionTitle:  'Documentos',
    uploadButton:  'Subir documento',
    previewButton: 'Ver documento',
    noDocuments:   'No hay documentos cargados aún.',
    uploadModalTitle: 'Subir documento',
    fields: {
      tipo:             'Tipo de documento',
      certificadoTipo:  'Tipo de certificado',
      otrosTexto:       'Descripción del certificado',
      fechaVencimiento: 'Fecha de vencimiento',
      archivo:          'Archivo',
    },
    placeholders: {
      tipo:            'Seleccioná el tipo',
      certificadoTipo: 'Seleccioná el tipo de certificado',
      otrosTexto:      'Describí el certificado (máx. 80 caracteres)',
      fechaVencimiento:'Fecha de vencimiento',
    },
    tipos: {
      dni:           'DNI',
      licencia:      'Licencia de conducir',
      foto_carnet:   'Foto carnet 4×4',
      certificado:   'Certificado',
      estudio_medico:'Estudio médico',
    },
    certificadoTipos: {
      gwo:               'GWO',
      cursos_elevadores: 'Cursos elevadores',
      espacio_confinado: 'Espacio confinado',
      manejo_defensivo:  'Manejo defensivo',
      cursos_vestas:     'Cursos Vestas',
      otros:             'Otros',
    },
    hints: {
      otrosTexto:       'Requerido cuando el tipo es "Otros".',
      fechaVencimiento: 'Requerida para certificados con vencimiento.',
      archivo:          'PDF o imagen, máximo 10 MB.',
      purgatorio:       'Tu documento será revisado por Administración.',
    },
    messages: {
      uploadSuccess: 'Documento enviado. Quedará Pendiente hasta que Administración lo apruebe.',
      uploadError:   'Error al subir el documento.',
      uploadingMsg:  'Subiendo documento...',
    },
    table: {
      tipo:             'Tipo',
      archivo:          'Archivo',
      vencimiento:      'Vencimiento',
      estado:           'Estado',
      fecha:            'Fecha de carga',
      acciones:         'Acciones',
    },
    statusBanner: {
      pendiente: 'Pendiente de aprobación.',
      aprobado:  'Documento aprobado.',
      rechazado: 'Documento rechazado.',
    },
    rechazadoBanner: 'Motivo del rechazo',
    archivoEliminado: 'Archivo eliminado por retención (30 días)',
    errors: {
      archivoRequerido:         'Seleccioná un archivo para subir.',
      tipoNoPermitido:          'Tipo de documento no permitido.',
      certificadoTipoRequerido: 'Seleccioná el tipo de certificado.',
      descripcionRequerida:     'La descripción del certificado es requerida.',
      descripcionMaxima:        'La descripción no puede superar los 80 caracteres.',
      archivoDemasiadoGrande:   'El archivo excede el límite de 10 MB.',
      tipoArchivoNoPermitido:   'Tipo de archivo no permitido:',
      urlNoDisponible:          'No se pudo generar la URL de acceso.',
      cargaError:               'No se pudieron cargar los documentos. Intentá recargar la página.',
    },
  },

  solicitudAusencia: {
    formTitle:    'Solicitud de Ausencia',
    submitButton: 'Enviar solicitud',
    fields: {
      motivo:      'Motivo',
      fechaInicio: 'Fecha de inicio',
      fechaFin:    'Fecha de fin',
      motivoOtros: 'Detalle del motivo',
      nota:        'Nota',
    },
    placeholders: {
      motivo:      'Seleccioná el motivo',
      motivoOtros: 'Describí el motivo (máx. 80 caracteres)',
      nota:        'Agregá una aclaración (opcional).',
    },
    messages: {
      success:      'Solicitud enviada. Quedará Pendiente hasta que Administración la apruebe.',
      // FB-ADJ-01: éxito distinto para admin — su envío se auto-aprueba, no
      // pasa por la bandeja de Aprobaciones.
      successAdmin: 'Solicitud enviada y aprobada automáticamente.',
      enviando:     'Enviando...',
    },
    // FB-ADJ-01: diálogo de confirmación previo al envío, solo para admin
    // (su solicitud se auto-aprueba, no pasa por revisión).
    adminConfirm: {
      title:   'Confirmar envío',
      message: 'Como administrador, esta solicitud se aprueba automáticamente y no pasa por revisión. ¿Confirmás el envío?',
      confirm: 'Confirmar envío',
      cancel:  'Cancelar',
    },
    errors: {
      motivoRequerido:          'Seleccioná un motivo.',
      fechaRequerida:           'Seleccioná las fechas de inicio y fin.',
      fechaFinAnteriorAInicio:  'La fecha de fin no puede ser anterior a la fecha de inicio.',
      fechaRetroactiva:         'No podés solicitar una ausencia que empiece antes de hoy.',
      motivoOtrosRequerido:     'Describí el motivo.',
      motivoOtrosMaximo:        'El detalle no puede superar los 80 caracteres.',
      pendienteDuplicada:       'Ya tenés una solicitud pendiente que se superpone con estas fechas. Resolvela antes de pedir otra.',
    },
    listTitle:     'Mis solicitudes',
    noSolicitudes: 'No hay solicitudes registradas aún.',
    table: {
      motivo:         'Motivo',
      fecha:          'Fecha',
      nota:           'Nota',
      estado:         'Estado',
      motivoRechazo:  'Motivo del rechazo',
      postAprobacion: 'Cambio posterior',
    },
    estados: {
      pendiente: 'Pendiente',
      aprobado:  'Aprobada',
      rechazado: 'Rechazada',
    },
    saldo: {
      title:           'Días de trámite',
      restantesPrefix: 'Te quedan',
      restantesSufijo: 'días de trámite este año.',
      sinDisponibles:  'No te quedan días de trámite disponibles este año.',
      excedido:        'Superaste el tope de días de trámite de este año.',
      fechasTitle:     'Fechas usadas este año',
      sinFechas:       'Todavía no usaste ningún día de trámite este año.',
    },
  },

  solicitudPasaje: {
    formTitle:    'Solicitud de Pasaje',
    submitButton: 'Enviar solicitud',
    fields: {
      empleado:    'Empleado',
      motivoViaje: 'Motivo del viaje',
      origen:      'Origen',
      destino:     'Destino',
      diasViaje:   'Días de viaje',
      nota:        'Nota',
    },
    placeholders: {
      empleado:    'Seleccioná un integrante de tu equipo',
      motivoViaje: 'Seleccioná el motivo',
      origen:      'Ej: Mendoza',
      destino:     'Ej: Bahía Blanca',
      nota:        'Agregá una aclaración (opcional).',
    },
    motivos: {
      inicio_franco:      'Inicio de franco',
      fin_franco:         'Fin de franco',
      traslado_proyectos: 'Traslado entre proyectos',
    },
    diasViaje: {
      agregarDia: 'Agregar día',
      quitarDia:  'Quitar',
    },
    messages: {
      success:      'Solicitud enviada. Quedará Pendiente hasta que Administración la apruebe.',
      // FB-ADJ-01: éxito distinto para admin — su envío se auto-aprueba, no
      // pasa por la bandeja de Aprobaciones.
      successAdmin: 'Solicitud enviada y aprobada automáticamente.',
      enviando:     'Enviando...',
    },
    // FB-ADJ-01: diálogo de confirmación previo al envío, solo para admin
    // (su solicitud se auto-aprueba, no pasa por revisión).
    adminConfirm: {
      title:   'Confirmar envío',
      message: 'Como administrador, esta solicitud se aprueba automáticamente y no pasa por revisión. ¿Confirmás el envío?',
      confirm: 'Confirmar envío',
      cancel:  'Cancelar',
    },
    errors: {
      empleadoRequerido:     'Seleccioná para quién es el pasaje.',
      empleadoFueraDeEquipo: 'Solo podés pedir pasajes para vos o para tu equipo.',
      motivoRequerido:       'Seleccioná el motivo del viaje.',
      origenRequerido:       'Ingresá el origen.',
      destinoRequerido:      'Ingresá el destino.',
      diasRequeridos:        'Agregá al menos un día de viaje.',
      diaRetroactivo:        'No podés solicitar un pasaje con un día de viaje anterior a hoy.',
    },
    listTitle:     'Mis solicitudes',
    noSolicitudes: 'No hay solicitudes registradas aún.',
    table: {
      empleado:       'Empleado',
      motivo:         'Motivo',
      recorrido:      'Recorrido',
      dias:           'Días de viaje',
      nota:           'Nota',
      estado:         'Estado',
      motivoRechazo:  'Motivo del rechazo',
      postAprobacion: 'Cambio posterior',
    },
    estados: {
      pendiente: 'Pendiente',
      aprobado:  'Aprobada',
      rechazado: 'Rechazada',
    },
    // FB-F4-15: "Mis solicitudes" ahora incluye pasajes donde el usuario es
    // solicitante O empleado viajero — dos perspectivas posibles sobre la
    // misma fila, así que el label de "para quién" cambia según quién sea.
    detalle: {
      paraLabel:     'Para',
      pedidoPorLabel:'Pedido por',
    },
  },

  adminEmpleado: {
    selectorTitle:       'Administrar perfil de empleado',
    selectorPlaceholder: 'Buscar por nombre o correo…',
    selectorHint:        'Ingresá al menos 2 caracteres.',
    noResults:           'Sin resultados.',
    pageTitle:           'Perfil de empleado',
    backButton:          'Volver a Mi Perfil',
    adminUploadHint:     'Como administrador, el archivo quedará aprobado directamente.',
  },

  aprobaciones: {
    title:    'Aprobaciones',
    subtitle: 'Bandeja única de solicitudes pendientes',
    noItems:  'No hay solicitudes pendientes.',
    table: {
      tipo:       'Tipo',
      usuario:    'Usuario',
      detalle:    'Detalle',
      fecha:      'Fecha',
      estado:     'Estado',
      acciones:   'Acciones',
    },
    tipos: {
      documento:  'Documento',
      pasaje:     'Pasaje',
      ausencia:   'Ausencia',
    },
    actions: {
      aprobar:   'Aprobar',
      rechazar:  'Rechazar',
      ver:       'Ver',
    },
    rejectModal: {
      title:       'Rechazar solicitud',
      motivoLabel: 'Motivo del rechazo',
      motivoPlaceholder: 'Explicá el motivo para que el usuario pueda corregir y reenviar.',
      motivoRequired: 'El motivo del rechazo es requerido.',
      confirm:     'Confirmar rechazo',
    },
    messages: {
      approveSuccess:     'Solicitud aprobada.',
      approveError:       'Error al aprobar la solicitud.',
      rejectSuccess:      'Solicitud rechazada.',
      rejectError:        'Error al rechazar la solicitud.',
      alreadyResolved:    'Esta solicitud ya fue resuelta.',
      resolvedEmailFailed: 'Resuelto; no se pudo enviar el mail.',
    },
    badgeSaldo: {
      usado:   'Usó',
      de:      'de',
      excede:  'excede',
      error:   'No se pudo calcular el saldo.',
    },
    sobrescritura: {
      aviso:       'Al aprobar, estos días se sobrescriben a período fuera de trabajo.',
      avisoPasaje: 'Al aprobar, estos días se sobrescriben a en viaje.',
      error:       'No se pudo calcular la previsualización de sobrescritura.',
    },
    detallePasaje: {
      paraLabel: 'Para',
    },
    verAprobadas: 'Ver aprobadas',
  },

  aprobadas: {
    title:    'Solicitudes Aprobadas',
    subtitle: 'Ausencias y pasajes ya aprobados. Cancelalos o editá sus fechas si hace falta.',
    noItems:  'No hay solicitudes aprobadas.',
    volverAprobaciones: 'Volver a Aprobaciones',
    filtro: {
      label:       'Filtrar por empleado',
      placeholder: 'Todos los empleados',
    },
    table: {
      tipo:      'Tipo',
      empleado:  'Empleado',
      detalle:   'Detalle',
      fecha:     'Fecha',
      marca:     'Cambio post-aprobación',
      acciones:  'Acciones',
    },
    marca: {
      comentarioLabel: 'Motivo',
      fechaLabel:       'Fecha del cambio',
      sinCambios:       '—',
    },
    actions: {
      cancelar:     'Cancelar',
      editarFechas: 'Editar fechas',
    },
    cancelModal: {
      title:               'Cancelar solicitud aprobada',
      warning:              'Se van a liberar los días asignados en el calendario del empleado. Esta acción no se puede deshacer.',
      comentarioLabel:      'Motivo del cambio',
      comentarioPlaceholder:'Explicá por qué se cancela esta solicitud — el empleado lo va a ver.',
      comentarioRequired:   'El comentario es obligatorio.',
      confirm:              'Confirmar cancelación',
    },
    editModal: {
      title:                 'Editar fechas',
      fechaInicioLabel:      'Nueva fecha de inicio',
      fechaFinLabel:         'Nueva fecha de fin',
      diaLabel:              'Día de viaje',
      agregarDia:            'Agregar día',
      quitarDia:             'Quitar',
      comentarioLabel:       'Motivo del cambio',
      comentarioPlaceholder: 'Explicá por qué se editan estas fechas — el empleado lo va a ver.',
      comentarioRequired:    'El comentario es obligatorio.',
      confirm:               'Confirmar edición',
      previewLoading:        'Calculando previsualización…',
      previewButton:         'Previsualizar sobrescritura',
    },
    errors: {
      comentarioRequerido:      'El comentario es obligatorio.',
      fechaRequerida:            'Seleccioná las fechas nuevas.',
      fechaFinAnteriorAInicio:   'La fecha de fin no puede ser anterior a la fecha de inicio.',
      fechaRetroactiva:          'No podés elegir una fecha anterior a hoy.',
      diasRequeridos:            'Agregá al menos un día de viaje.',
      diaRetroactivo:            'No podés elegir un día de viaje anterior a hoy.',
      lifoBloqueo:               'No se puede completar esta acción: hay solicitudes aprobadas más recientes que se superponen en fechas y hay que resolver primero:',
      yaNoVigente:               'Esta solicitud ya no está vigente — puede haber sido cancelada o editada por otro admin. Recargá la página.',
      generic:                   'Error al procesar el cambio.',
    },
    messages: {
      cancelSuccess: 'Solicitud cancelada.',
      editSuccess:   'Fechas actualizadas.',
      emailFailed:   'Hecho; no se pudo enviar el mail al empleado.',
    },
    sobrescritura: {
      aviso: 'Estos días ya tienen una fila en el calendario del empleado — se van a sobrescribir.',
      error: 'No se pudo calcular la previsualización de sobrescritura.',
      vacio: 'Ninguno de los días nuevos tiene fila cargada en el calendario todavía.',
    },
  },

  emails: {
    documentoRechazado: {
      subject:     'Tu documento fue rechazado — First Blades',
      saludo:      'Hola',
      intro:       'Tu documento fue revisado por Administración y fue rechazado.',
      tipoLabel:   'Documento',
      motivoLabel: 'Motivo del rechazo',
      accion:      'Podés corregirlo y volver a enviarlo desde el portal, en la sección Mi Perfil.',
      firma:       'Equipo First Blades',
    },
    vencimientoEmpleado: {
      subject:          'Tu documento está por vencer — First Blades',
      saludo:           'Hola',
      intro:            'Uno de tus documentos está por vencer.',
      tipoLabel:        'Documento',
      vencimientoLabel: 'Fecha de vencimiento',
      diasLabel:        'Días restantes',
      accion:           'Actualizalo desde el portal, en la sección Mi Perfil, antes de que venza.',
      firma:            'Equipo First Blades',
    },
    vencimientoAdmin: {
      subject:          'Documento de un empleado por vencer — First Blades',
      intro:            'El documento de un integrante del equipo está por vencer.',
      empleadoLabel:    'Empleado',
      tipoLabel:        'Documento',
      vencimientoLabel: 'Fecha de vencimiento',
      diasLabel:        'Días restantes',
      firma:            'Equipo First Blades',
    },
    alertaFranco: {
      subject:       'Alerta de descanso de un empleado — First Blades',
      intro:         'Un empleado alcanzó una alerta de descanso en el Calendario de rotaciones.',
      empleadoLabel: 'Empleado',
      alertaLabel:   'Alerta',
      accion:        'Podés ver el detalle en el Calendario del portal, sección Alertas de descanso.',
      firma:         'Equipo First Blades',
    },
    ausenciaAprobada: {
      subject:      'Tu solicitud de ausencia fue aprobada — First Blades',
      saludo:       'Hola',
      intro:        'Tu solicitud de ausencia fue revisada por Administración y fue aprobada.',
      motivoLabel:  'Motivo',
      periodoLabel: 'Período',
      accion:       'Ya podés verla reflejada en el Calendario del portal.',
      firma:        'Equipo First Blades',
    },
    ausenciaRechazada: {
      subject:            'Tu solicitud de ausencia fue rechazada — First Blades',
      saludo:             'Hola',
      intro:              'Tu solicitud de ausencia fue revisada por Administración y fue rechazada.',
      motivoLabel:        'Motivo',
      periodoLabel:       'Período',
      motivoRechazoLabel: 'Motivo del rechazo',
      accion:             'Podés volver a enviarla desde el portal, en la sección Solicitud de Ausencia.',
      firma:              'Equipo First Blades',
    },
    pasajeAprobado: {
      subject:        'Tu solicitud de pasaje fue aprobada — First Blades',
      saludo:         'Hola',
      intro:          'Tu solicitud de pasaje fue revisada por Administración y fue aprobada.',
      motivoLabel:    'Motivo',
      recorridoLabel: 'Recorrido',
      diasLabel:      'Días de viaje',
      accion:         'Ya podés verlo reflejado en el Calendario del portal.',
      firma:          'Equipo First Blades',
    },
    pasajeRechazado: {
      subject:            'Tu solicitud de pasaje fue rechazada — First Blades',
      saludo:             'Hola',
      intro:              'Tu solicitud de pasaje fue revisada por Administración y fue rechazada.',
      motivoLabel:        'Motivo',
      recorridoLabel:     'Recorrido',
      diasLabel:          'Días de viaje',
      motivoRechazoLabel: 'Motivo del rechazo',
      accion:             'Podés volver a enviarla desde el portal, en la sección Solicitud de Pasaje.',
      firma:              'Equipo First Blades',
    },
    ausenciaCancelada: {
      subject:        'Tu solicitud de ausencia fue cancelada — First Blades',
      saludo:         'Hola',
      intro:          'Una solicitud de ausencia tuya, ya aprobada, fue cancelada por Administración.',
      motivoLabel:    'Motivo',
      periodoLabel:   'Período cancelado',
      comentarioLabel:'Por qué',
      accion:         'Podés ver el detalle en la sección Solicitud de Ausencia del portal.',
      firma:          'Equipo First Blades',
    },
    ausenciaEditada: {
      subject:          'Se editaron las fechas de tu ausencia — First Blades',
      saludo:           'Hola',
      intro:            'Una solicitud de ausencia tuya, ya aprobada, tuvo sus fechas editadas por Administración.',
      motivoLabel:      'Motivo',
      periodoAnteriorLabel: 'Fechas anteriores',
      periodoNuevoLabel:    'Fechas nuevas',
      comentarioLabel:  'Por qué',
      accion:           'Podés ver el detalle en la sección Solicitud de Ausencia del portal.',
      firma:            'Equipo First Blades',
    },
    pasajeCancelado: {
      subject:        'Tu solicitud de pasaje fue cancelada — First Blades',
      saludo:         'Hola',
      intro:          'Una solicitud de pasaje tuya, ya aprobada, fue cancelada por Administración.',
      motivoLabel:    'Motivo',
      recorridoLabel: 'Recorrido',
      diasLabel:      'Días cancelados',
      comentarioLabel:'Por qué',
      accion:         'Podés ver el detalle en la sección Solicitud de Pasaje del portal.',
      firma:          'Equipo First Blades',
    },
    pasajeEditado: {
      subject:            'Se editaron los días de tu pasaje — First Blades',
      saludo:             'Hola',
      intro:              'Una solicitud de pasaje tuya, ya aprobada, tuvo sus días editados por Administración.',
      motivoLabel:        'Motivo',
      recorridoLabel:     'Recorrido',
      diasAnterioresLabel:'Días anteriores',
      diasNuevosLabel:    'Días nuevos',
      comentarioLabel:    'Por qué',
      accion:             'Podés ver el detalle en la sección Solicitud de Pasaje del portal.',
      firma:              'Equipo First Blades',
    },
  },

  errors: {
    unauthorized:   'No tenés permiso para acceder a esta sección.',
    sessionExpired: 'Tu sesión expiró. Iniciá sesión nuevamente.',
    generic:        'Ocurrió un error inesperado. Intentá nuevamente.',
    notFound:       'Página no encontrada.',
  },

  topbar: {
    notifications: 'Notificaciones',
    userMenu:      'Menú de usuario',
    menuButton:    'Menú',
  },

  miEquipo: {
    title:      'Mi Equipo',
    subtitle:   'Perfiles de los técnicos de tu equipo',
    noMiembros: 'No hay miembros en tu equipo.',
    table: {
      nombre:   'Nombre',
      email:    'Correo electrónico',
      telefono: 'Teléfono',
      estado:   'Estado',
      rol:      'Rol',
    },
    detalle: {
      backToList:   'Volver a Mi Equipo',
      noEncontrado: 'Miembro no encontrado.',
      sinDatos:     '—',
    },
    campos: {
      nombre:   'Nombre',
      email:    'Correo electrónico',
      telefono: 'Teléfono',
      estado:   'Estado',
      rol:      'Rol',
    },
  },

  equipo: {
    title:   'Equipo',
    subtitle: 'Estado documental de todos los perfiles',
    search:   'Buscar por nombre o correo…',
    filtroEstado: 'Estado',
    todoEstado:   'Todos los estados',
    noPerfiles:   'No hay perfiles registrados.',
    table: {
      nombre:       'Nombre',
      email:        'Correo electrónico',
      rol:          'Rol',
      supervisor:   'Supervisor',
      estado:       'Estado',
      docVencidos:  'Vencidos',
      docPorVencer: 'Por vencer',
    },
    proximosAVencer: {
      title:    'Próximos a vencer',
      subtitle: 'Documentos vencidos o que vencen en los próximos 30 días',
      noItems:  'No hay documentos próximos a vencer.',
      table: {
        empleado:      'Empleado',
        documento:     'Documento',
        vencimiento:   'Vencimiento',
        diasRestantes: 'Días restantes',
      },
    },
    diasHoy:   'Hoy',
    diasHace:  'Hace',
    diasLabel: 'días',
    diaLabel:  'día',
  },

  calendario: {
    title:    'Calendario',
    subtitle: 'Calendario de rotación',
    meses: [
      'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
      'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
    ],
    nav: {
      mesAnterior: 'Mes anterior',
      mesSiguiente: 'Mes siguiente',
      hoy:          'Hoy',
    },
    table: {
      empleado: 'Empleado',
    },
    leyenda: {
      title:      'Referencias',
      sinCargar:  'Sin asignar',
      estimado:   'Planificado',
    },
    noEmpleados: 'No hay empleados activos para mostrar en el roster.',
    modal: {
      title:  'Editar día',
      guardar: 'Guardar',
      fields: {
        empleado:  'Empleado',
        fecha:     'Fecha',
        estado:    'Estado',
        motivo:    'Motivo',
        motivoOtros: 'Detalle del motivo',
        estimado:  'Planificado (a futuro)',
      },
      placeholders: {
        motivo:      'Seleccioná el motivo',
        motivoOtros: 'Describí el motivo (máx. 80 caracteres)',
      },
      hints: {
        estimado: 'Los días planificados se muestran en tono más claro hasta 7 días antes de la fecha.',
      },
    },
    motivos: {
      vacaciones:      'Vacaciones',
      licencia_medica: 'Licencia médica',
      dia_tramite:     'Día de trámite',
      matrimonio:      'Matrimonio',
      fallecimiento:   'Fallecimiento',
      otros:           'Otros',
    },
    range: {
      modal: {
        title:   'Aplicar a varios días',
        guardar: 'Aplicar',
        cerrar:  'Cerrar',
        rango:   'Rango',
      },
      seleccion: {
        diaSingular: 'día seleccionado',
        diasPlural:  'días seleccionados',
        anclaHint:   'Elegí el último día del rango con shift-click, o presioná Esc para cancelar.',
      },
      resultado: {
        aplicaronPrefijo: 'Se aplicaron',
        de:               'de',
        diaSingular:      'día',
        diasPlural:       'días',
        fallaronTitulo:   'No se pudieron aplicar estos días:',
      },
      errors: {
        diaTramiteNoDisponible:
          'El motivo "Día de trámite" no está disponible acá: se gestiona por Solicitud de Ausencia con aprobación del admin.',
        permisoDenegado: 'No tenés permiso para modificar este día.',
        diaFallidoGenerico: 'No se pudo guardar este día.',
      },
    },
    dashboard: {
      title:    'Resumen de ausencias del mes',
      subtitle: 'Días por motivo, por empleado, en el mes visible.',
      total:    'Total',
    },
    alertasFranco: {
      title:      'Alertas de descanso',
      subtitle:   'Empleados con muchos días trabajados sin descanso o con franco prolongado.',
      sinAlertas: 'Sin alertas de descanso.',
      table: {
        empleado: 'Empleado',
        tipo:     'Alerta',
      },
      tipos: {
        sin_franco:       'días sin descanso',
        franco_excedido:  'días de franco prolongado',
      },
    },
    saldoDiasTramite: {
      title:        'Saldo de días de trámite',
      subtitle:     'Días de trámite usados y disponibles este año, por empleado.',
      sinEmpleados: 'No hay empleados activos para mostrar.',
      table: {
        empleado:  'Empleado',
        usados:    'Usados',
        restantes: 'Restantes',
        estado:    'Estado',
      },
      estados: {
        disponible: 'Disponible',
        excedido:   'Excedido',
      },
    },
    filtroEmpleado: {
      label:         'Filtrar por empleado',
      todos:         'Todos los empleados',
      seleccionado:  'seleccionado',
      seleccionados: 'seleccionados',
      limpiar:       'Limpiar filtro',
    },
    errors: {
      motivoRequerido:      'Seleccioná un motivo para "Fuera del trabajo".',
      motivoOtrosRequerido: 'Describí el motivo cuando seleccionás "Otros".',
      motivoOtrosMaximo:    'El detalle del motivo no puede superar los 80 caracteres.',
    },
    messages: {
      upsertSuccess: 'Día actualizado correctamente.',
      upsertError:   'Error al actualizar el día.',
      loadError:     'No se pudo cargar el roster del mes.',
    },
  },

  pages: {
    dashboard: {
      title:       'Inicio',
      subtitle:    'Bienvenido al portal',
      welcome:     'Bienvenido al Portal First Blades',
      loggedAs:    'Ingresaste como',
      hint:        'Seleccioná una opción del menú lateral para comenzar.',
    },
    miPerfil: {
      title:    'Mi Perfil',
      subtitle: 'Tus datos personales y documentos',
    },
    equipo: {
      title:    'Equipo',
      subtitle: 'Estado documental de todos los perfiles',
    },
    miEquipo: {
      title:    'Mi Equipo',
      subtitle: 'Perfiles de los técnicos de tu equipo',
    },
    calendario: {
      title:    'Calendario',
      subtitle: 'Calendario de rotación',
    },
    solicitudPasaje: {
      title:    'Solicitud de Pasaje',
      subtitle: 'Gestioná tus pedidos de traslado',
    },
    solicitudAusencia: {
      title:    'Solicitud de Ausencia',
      subtitle: 'Gestioná tus pedidos de ausencia',
    },
    aprobaciones: {
      title:    'Aprobaciones',
      subtitle: 'Bandeja de solicitudes pendientes',
    },
    procedimientos: {
      title:    'Procedimientos / Políticas',
      subtitle: 'Documentos y normativa interna',
    },
    rendicionGastos: {
      title:    'Rendición de Gastos',
      subtitle: 'Acceso externo a Google Workspace',
    },
    formularios: {
      title:    'Ingreso',
      subtitle: 'Formularios de ingreso y precarga',
    },
    gestionUsuarios: {
      title:    'Gestión de Usuarios',
      subtitle: 'Administrá los usuarios del portal',
    },
  },
} as const;
