-- setup.sql — obsoleto desde FB-F1-07.
-- El stack de Supabase real (supabase start) provee auth, storage y roles.
-- Este archivo se conserva para no romper referencias históricas; no tiene efecto.
